version: "2"
services:
  user-service:
    image: registry.gitlab.com/barugoo/user-service
    ports:
      - "8083:8080"
  auth-service:
    image: registry.gitlab.com/barugoo/auth-service
    ports:
      - "8084:8080"
